name: Java Maven Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        default: '.'
        type: string
      use-mvn-cache:
        default: true
        required: false
        type: boolean
      java-version:
        default: '21'
        required: false
        type: string
      java-distribution:
        default: 'temurin'
        required: false
        type: string
      surefire-report:
        default: true
        required: false
        type: boolean
      deploy-jars:
        default: true
        required: false
        type: boolean
      code-format-check:
        default: true
        required: false
        type: boolean
    secrets:
      ARTEFACT_REPO_USER:
        description: 'Artefact repository user'
        required: true
      ARTEFACT_REPO_PASSWORD:
        description: 'Artefact repository password'
        required: true
jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: maven

      - name: Cache local Maven repository
        if: inputs.use-mvn-cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Code format check
        if: inputs.code-format-check
        run: ./mvnw com.spotify.fmt:fmt-maven-plugin:check

      - name: Compile
        run: ./mvnw clean compile --file pom.xml

      - name: Test
        run: ./mvnw verify --batch-mode --fail-at-end --errors --file pom.xml

      - name: Configure maven for deploy
        if: inputs.deploy-jars
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id": "linkyard.repo", "username": "${env.ARTEFACT_REPO_USER}", "password": "${env.ARTEFACT_REPO_PASSWORD}" }]'

      - name: Deploy to artefact server
        if:  (contains(github.ref, 'deploy') || contains(github.ref, 'release') || github.ref == 'refs/heads/main') && inputs.deploy-jars
        env:
          ARTEFACT_REPO_USER: ${{ secrets.ARTEFACT_REPO_USER }}
          ARTEFACT_REPO_PASSWORD: ${{ secrets.ARTEFACT_REPO_PASSWORD }}
        run: ./mvnw -Dmaven.test.skip=true -DskipTests deploy

      - name: Publish Test Report
        if: inputs.surefire-report && (success() || failure())
        uses: scacap/action-surefire-report@v1
