name: Java Maven Build

on:
  workflow_call:
    inputs:
      java-version:
        default: '21'
        required: false
        type: string
      java-distribution:
        default: 'temurin'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: maven
      - name: compile
        run: mvn clean compile -U --file pom.xml
      - name: test
        run: mvn verify --file pom.xml
