name: Java Maven Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        default: '.'
        type: string
      use-mvn-cache:
        default: true
        required: false
        type: boolean
      use-jib:
        default: true
        required: false
        type: boolean
      use-jib-cache:
        default: true
        required: false
        type: boolean
      java-version:
        default: '21'
        required: false
        type: string
      java-distribution:
        default: 'temurin'
        required: false
        type: string
      surefire-report:
        default: true
        required: false
        type: boolean
    secrets:
      CONTAINER_REGISTRY_USER:
        description: 'Container registry user'
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: 'Container registry password'
        required: true
jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set SHORT_COMMIT_SHA
        run: echo "SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Set TIMESTAMP_VERSION
        run: echo "TIMESTAMP_VERSION=$(date +%Y%m%d%H%M)" >> "$GITHUB_ENV"

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: maven

      - name: Cache local Maven repository
        if: inputs.use-mvn-cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install xml parser
        run: sudo apt install libxml2-utils

      - name: Find and Parse pom.xml
        id: parse-pom
        run: |
          imageNames=()
          find . -type f -name "pom.xml" -print0 | while IFS= read -r -d '' file; do
            echo "Parsing $file"
            imageName=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="properties"]/*[local-name()="docker.image.name"]/text()' "$file")
            imageNames+=("$imageName")
          done
          echo "CONTAINER_IMAGE_NAMES=$imageNames" >> "$GITHUB_OUTPUT"

      - name: Use Array Output
        env:
          CONTAINER_IMAGE_NAMES: ${{ steps.parse-pom.outputs.CONTAINER_IMAGE_NAMES }}
        run: |
          # Assign the output to a variable
          myArray = $CONTAINER_IMAGE_NAMES
          
          # Use the array
          for item in "${myArray[@]}"; do
            echo $item
          done

      - name: Compile
        run: ./mvnw clean compile -U -Dchangelist=${{ env.TIMESTAMP_VERSION }} --file pom.xml

      - name: Test
        run: ./mvnw verify --batch-mode --fail-at-end --errors -Dchangelist=${{ env.TIMESTAMP_VERSION }} --file pom.xml

      - name: Publish Test Report
        if: inputs.surefire-report && (success() || failure())
        uses: scacap/action-surefire-report@v1

      - name: Login to container registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: docker.nexus.itbs.linkyard-cloud.ch
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Cache JIB images and base images
        if: github.ref == 'refs/heads/main' && inputs.use-jib && inputs.use-jib-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/google-cloud-tools-java
          key: ${{ runner.os }}-jib
          restore-keys: |
            ${{ runner.os }}-jib

      - name: Build container with JIB
        if: github.ref == 'refs/heads/main' && inputs.use-jib
        run: ./mvnw package jib:build -Dmaven.test.skip=true -Dchangelist=${{ env.TIMESTAMP_VERSION }} -Ddocker.image.version=${{ env.SHORT_COMMIT_SHA }}

      - name: Output home
        run: ls -la ~/.cache/google-cloud-tools-java
